sudo: false
language: python
python: '3.5'
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - pip install -e ".[test]"
script:
  - isort --recursive --diff infinity.py test_infinity.py && isort --recursive --check-only infinity.py test_infinity.py
  - flake8 infinity.py test_infinity.py
  - py.test --doctest-glob='*.rst'
