sudo: required
dist: xenial
language: python
python: '3.5'
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy3
install:
  - pip install -e ".[test]"
script:
  - isort --recursive --diff infinity.py test_infinity.py && isort --recursive --check-only infinity.py test_infinity.py
  - flake8 infinity.py test_infinity.py
  - py.test --doctest-glob='*.rst'
